-- Active: 1700068523370@@127.0.0.1@3306
DROP DATABASE IF EXISTS 5to_HospedApp2023 ;
CREATE DATABASE 5to_HospedApp2023 ;
USE 5to_HospedApp2023 ;


CREATE TABLE Hotel(
IdHotel SMALLINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(64) NOT NULL,
Domicilio VARCHAR(64) NOT NULL,
Email VARCHAR(64) NOT NULL UNIQUE,
Contrasena CHAR(64) NOT NULL,
Estrella TINYINT UNSIGNED NOT NULL
);


CREATE TABLE Cama (
IdCama TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(64) NOT NULL UNIQUE,
Pueden_dormir TINYINT UNSIGNED NOT NULL
);


CREATE TABLE Cuarto (
IdCuarto TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Cochera BOOL NOT NULL,
Noche DOUBLE NOT NULL,
Descripcion VARCHAR(60) UNIQUE
	);

CREATE TABLE Hotel_Cuarto (
	IdHotel SMALLINT UNSIGNED,
	IdCuarto TINYINT UNSIGNED,
	Numero TINYINT UNSIGNED,
	CONSTRAINT PK_HotelCuarto PRIMARY KEY (IdHotel, IdCuarto),
	CONSTRAINT FK_HotelCuarto_Hotel Foreign Key (IdHotel) REFERENCES Hotel (IdHotel),
	CONSTRAINT FK_HotelCuarto_Cuarto Foreign Key (IdCuarto) REFERENCES Cuarto (IdCuarto)
);
CREATE TABLE Cuarto_Cama(
IdCuarto TINYINT UNSIGNED NOT NULL,
IdCama TINYINT UNSIGNED NOT NULL,
Cantidad_de_cama TINYINT UNSIGNED NOT NULL,
PRIMARY KEY (IdCuarto, IdCama),
CONSTRAINT FK_CuartoCama_Cuarto FOREIGN KEY (IdCuarto) REFERENCES Cuarto (IdCuarto),
CONSTRAINT FK_CuartoCama_Cama FOREIGN KEY (IdCama) REFERENCES Cama (IdCama)
);

CREATE TABLE Cliente (
Dni INT UNSIGNED PRIMARY KEY,
Nombre VARCHAR(64) NOT NULL,
Apellido VARCHAR(64) NOT NULL,
Email VARCHAR(64) NOT NULL UNIQUE,
Contrasena CHAR(64) NOT NULL
);


CREATE TABLE Reserva (
IdReserva SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
IdHotel SMALLINT UNSIGNED NOT NULL,
Inicio DATE NOT NULL,
Fin DATE NOT NULL,
Dni INT UNSIGNED NOT NULL,
IdCuarto TINYINT UNSIGNED NOT NULL,
Calificacion_del_cliente TINYINT UNSIGNED,
Calificacion_del_hotel TINYINT UNSIGNED,
Comentario_del_cliente VARCHAR(60),
CONSTRAINT FK_Reserva_Cliente FOREIGN KEY (Dni) REFERENCES Cliente (Dni),
CONSTRAINT FK_Reserva_Hotel_Cuarto FOREIGN KEY (IdCuarto) REFERENCES Hotel_Cuarto (IdCuarto),
CONSTRAINT FK_Reserva_HotelCuarto FOREIGN KEY (IdHotel) REFERENCES Hotel_Cuarto (IdHotel)
);


CREATE TABLE ReservaCancelado (
IdReserva SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
IdHotel SMALLINT UNSIGNED NOT NULL,
Inicio DATE NOT NULL,
Fin DATE NOT NULL,
Dni INT UNSIGNED NOT NULL,
IdCuarto TINYINT UNSIGNED NOT NULL,
CONSTRAINT FK_ReservaCancelado_Hotel FOREIGN KEY (IdHotel) REFERENCES Hotel (IdHotel),
CONSTRAINT FK_ReservaCancelado_Cliente FOREIGN KEY (Dni) REFERENCES Cliente (Dni),
CONSTRAINT FK_ReservaCancelado_Cuarto FOREIGN KEY (IdCuarto) REFERENCES Cuarto (IdCuarto)
);


